### ISSUE TITLE
[MIGRATED] Invalid share urls lead to blank projects

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2230] opened 2015-06-15 17:26 UTC
From a share url to a non-existent project, users are lead to an empty player. No errors, and easy to get out, but should probably just lead to the discover gallery with an error.

From #2223

**Comment by thisandagain** [comment] 2015-06-15 22:12
Good catch. :+1:

**Comment by jgmac1106** [comment] 2015-06-16 18:26
I am running into this issue. I searched the repo to see if the issue has been posted but here are my links to a project I made:
https://t.co/pRsVMds1pY 
This went through Twitter's url shortner using Plume for Android

I also tested if it was the url shortner and emailed myself the shared project and got this: https://beta.webmaker.org/users/1249/projects/514

Either way I am just brought to a blank screen and do not see the project I shared. Does it need to be opened only on other Android devices with webmaker installed to see someone's projects?

**Comment by thisandagain** [comment] 2015-06-16 18:52
:+1: Tracking the root cause of @jgmac1106 's issue here (on track to have resolved by EOW): https://github.com/mozilla/webmaker-desktop/issues/62

**Comment by toolness** [comment] 2015-07-14 19:29
<a href="https://github.com/mozilla/webmaker-core/issues/191"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/191.
Please don't comment on it here.

**Closed by toolness** 2015-07-14 19:29 UTC
Labels: bug
