### ISSUE TITLE
When editing the text element, the prompt should have the existing value of the text

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1755] opened 2015-05-10 04:39 UTC
Right now it's blank so if you want to make an edit, you have to retype it all.

**Comment by thisandagain** [comment] 2015-05-12 00:09
This is a dupe of the implementation ticket for the actual design of the text editor. @xmatthewx can you triage and close?

**Comment by xmatthewx** [comment] 2015-05-12 15:05
Text editing will be in the preview, not a modal, so this won't be a problem. #1644

**Closed by xmatthewx** 2015-05-12 15:05 UTC
Labels: feedback
