### ISSUE TITLE
missing npm start script

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/webmaker-android#2386] opened 2015-07-02 16:58 UTC
it's in the README, but i don't see it in the `package`. looks like it was removed here: https://github.com/mozilla/webmaker-android/commit/62efb245ee249dd13fb18ee071e6bebf6f75b4bd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2, by @gvn.

what are the new steps?

**Comment by gvn** [comment] 2015-07-02 17:09
Sorry: `npm run build`. New docs coming soooooon! :dancers:

**Comment by Pomax** [comment] 2015-07-06 19:30
suggestion: alias npm start so that it calls `npm run build`, since `npm start` is a built in known script, where as `build` requires that nasty "run" that people constantly forget (and because node-build is a real executable, it actually does *something*, just not the right thing at all, which can frustrate devs and contributors)

**Comment by gvn** [comment] 2015-07-13 17:45
Dupe of #2398

**Closed by gvn** 2015-07-13 17:45 UTC
Labels: bug
