### ISSUE TITLE
Zindex does not work on 4.2.2

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2177] opened 2015-06-12 11:13 UTC
On the Nexus 5 running 5.0 I can manage zindex super well

On the user's phone running 4.2.2 its impossible to bring an elements in the back. 
Steps: 
- Add text 
- add image
- move text over the image :+1: 
- Move text *behind* the image :-1: 

See phone specs below 
![img_20150612_165115](https://cloud.githubusercontent.com/assets/8261945/8128982/0df92bbe-1126-11e5-8e5c-bdf76fba2724.jpg)

**Comment by thisandagain** [comment] 2015-06-12 19:03
I'm having trouble replicating this on some of our test devices but I can confirm that it seems to be related to CPU speed vs. Android OS version. I'm going to continue to dig into this next week.

**Comment by thisandagain** [comment] 2015-06-15 19:17
Resolved in #2227

**Closed by thisandagain** 2015-06-15 19:17 UTC
Labels: bug
