### ISSUE TITLE
Some text blocks are disapearing in page edit but still visible in map view 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1780] opened 2015-05-11 10:06 UTC
I had 2 text boxes, one completely disapeared when I was on page edit.
But surprisingly re-appears when on map view. It's the hello world box in the screenshots attached. 

Page edit - "Hello World" not here 
![screenshot_2015-05-11-10-59-50](https://cloud.githubusercontent.com/assets/8261945/7562558/45fb776e-f7cd-11e4-8457-7c145f094dba.png)

Map view  - "Hello World" is here ! 
![screenshot_2015-05-11-10-59-42](https://cloud.githubusercontent.com/assets/8261945/7562600/979f5388-f7cd-11e4-8dbb-a289fcbb7973.png)

**Comment by thisandagain** [comment] 2015-05-12 00:49
Duplicate of #1745

**Closed by thisandagain** 2015-05-12 00:49 UTC
Labels: bug, feedback
