### ISSUE TITLE
Strange behaviour backspacing while editing text element copy

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1958] opened 2015-05-20 22:45 UTC
Steps to reproduce
* Add a text element
* Edit it
* Tap the "Hello world" preview text to edit it
* Caret is placed at the end of the copy
* Hit Backspace on the android keyboard
* The copy suddenly changes to "Hello worldworl"

**Comment by xmatthewx** [comment] 2015-06-01 19:19
duplicate of #2050

**Closed by xmatthewx** 2015-06-01 19:19 UTC
Labels: bug, feedback
