### ISSUE TITLE
The wrong element is highlighted as "selected" after editing another element.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1972] opened 2015-05-21 17:40 UTC
Steps to reproduce
* Create a new project
* Edit the starting page
* Add a text element
* Immediately add an image element
* Edit the image and change any property
* Go back to the Page editor
* The elements have swapped positions

**Comment by k88hudson** [comment] 2015-05-21 19:51
@flukeout this should be resolved by the latest build.

**Comment by thisandagain** [comment] 2015-05-21 20:40
Confirmed resolved.

**Comment by flukeout** [comment] 2015-05-21 21:41
@k88hudson Still able to reproduce this on latest build. Let's hop on Vidyo and I can show you the steps in case you can't. Latest android on Nexus 4 device.

**Comment by secretrobotron** [comment] 2015-05-25 17:30
Me too. Just tried out latest nightly. Rage+1.

**Comment by secretrobotron** [comment] 2015-05-25 17:32
Blocks #1665

**Comment by Pomax** [comment] 2015-05-26 20:36
I can't seem to be able to reproduce this at all using today's build.

**Comment by thisandagain** [comment] 2015-05-26 20:38
@flukeout @secretrobotron Can you take a screen recording or some alternative STRs?

**Comment by flukeout** [comment] 2015-05-26 20:46
@thisandagain Let me try my old STRs first and see, maybe it's been fixed!

**Comment by flukeout** [comment] 2015-05-26 20:47
I can't reproduce the swapping but what is happening now is that after I edit the image, the image loses the selected border.

**Comment by flukeout** [comment] 2015-05-26 20:55
This is a gross recording but.. https://www.youtube.com/watch?v=8Ya_NKHscU0

**Comment by secretrobotron** [comment] 2015-05-27 18:32
Here's what I just tried
1. New project
2. Add a text element
3. Make it big
4. Add another text element, but don't touch it or anything else yet
5. Click the edit button
6. Edit it a bit
7. Go back and try to move the element you just edited (the newer one)

It looks like the wrong element is being selected, but it might be because it doesn't select new elements right away (you have to click on them first).

**Comment by secretrobotron** [comment] 2015-05-27 18:35
Actually, it seems like, once you're done editing something, the next thing you select will get the properties of the element that *should* have been edited.

**Comment by flukeout** [comment] 2015-05-27 18:36
@secretrobotron Vine or it didn't happen

**Comment by secretrobotron** [comment] 2015-05-27 18:37
I don't even.

**Comment by thisandagain** [comment] 2015-05-27 18:49
LOL ... I totally believe you and that makes sense given the bug we have identified. @Pomax is on the case.

**Comment by Pomax** [comment] 2015-05-29 16:24
fixed through https://github.com/mozilla/webmaker-android/pull/2025

**Closed by Pomax** 2015-05-29 16:24 UTC
Labels: bug, critical, feedback
