### ISSUE TITLE
Create project content for landing page & video 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1665] opened 2015-05-05 19:37 UTC
Discussed content options earlier with @vazquez @secretrobotron
 - Step 1 - write up or sketch a few ideas 
 - Step 2 - produce one high fidelity project
 - Step 3 - bring other ideas to community 

Things to consider:
 - photos of people are great
 - avoid illustrated assets
 - bonus points for a project that looks good in map view

Progress on this is less important than UI revisions for Alpha build, more important than UI for Beta build.

**Comment by vazquez** [comment] 2015-05-05 22:33
### Sketches

##### 1. Spotted on the Street: Graffiti
###### Category
Documentary
###### Description
A visual essay that shows exemplary works of graffiti art in Brooklyn, Portland, and Toronto. Each page contains a photo, title, and description.

![img_1292](https://cloud.githubusercontent.com/assets/1119821/7484220/0961c182-f33b-11e4-8c78-b52d8e8cc0f8.jpg)

---

##### 2. The Bucket List
###### Category
Blog
###### Description
The Bucket List is a collection of an individual's desire to visit certain places and live through distinct experiences. Each page contains a title, photo, and brief description as to why this is a unique place/destination.

![img_1293](https://cloud.githubusercontent.com/assets/1119821/7484243/37a935f2-f33b-11e4-8375-9edced88a81e.jpg)

---

##### 3. Happy People (Happiness on the Streets)
###### Category
Documentary
###### Description
A visual documentary of candid photography involving people smiling and having a good time. Watching people smile makes one smile, so I expect this project to address the human aspects that our app is trying to bring.

![img_1294](https://cloud.githubusercontent.com/assets/1119821/7484261/51309bdc-f33b-11e4-9ece-c38dd86b9fff.jpg)

**Comment by vazquez** [comment] 2015-05-05 22:33
Looping @thisandagain into the discussion since one of these projects will be used on the video and landing page.

**Comment by thisandagain** [comment] 2015-05-05 22:40
These are great! I really like how the first two are non-linear. The subject matter of the third feels really nice with our brand though. :smile:

**Comment by secretrobotron** [comment] 2015-05-06 14:17
Gotta say, I love those mini-maps.

**Comment by secretrobotron** [comment] 2015-05-06 14:49
##### Graffiti
* Great opportunity for nice photos.
* Good model for people on the ground who can re-make this project for their own locale.
* Love that it can double as a walking tour.
* Each path should have its own title screen to display city name (thinking about users that just swipe and disregard those buttons).

##### Bucket List
* Enjoying the ability for the list to grow over time.
* The order implied by the tile layout is a bit strange. Some meaning in that?
  * Maybe better to represent personal milestones? e.g. Find an interest, finish school, get a job, buy a house with pool, etc.?
  * Thinking: maybe one side represents things to do, and the other is things done?
* What would this look like as just a sprawling web of ideas? Like a mind-map?

##### Happiness
* Really like how this could extend to be a "pass it forward" sort of thing.
  * Then, the order of it makes sense.
* Great opportunity to show photos of happy faces (esp. local ones; friends).

**Comment by xmatthewx** [comment] 2015-05-06 15:10
I suggest we pursue **happiness**. Let's discuss. It seems like it'd be the quickest to build and the most valuable for promotion. 

It also connects to an opportunity @flukeout and I discussed in Toronto. This project could serve as a friend list. If a friend is also on Webmaker, add a button to a project of theirs with all their friends. It's a very flexible way to build groups w/o the platform dictating the nature of relationships.

**Comment by secretrobotron** [comment] 2015-05-06 15:17
:+1: agreed.

I'd say Graffiti is a contender though: people can link to each other's stories/tours. Equally easy to build (if we focus on areas of a city instead of many cities), great opportunity for nice images to display the places in which people live and use Webmaker. Seems to a have a bit wider application.

**Comment by vazquez** [comment] 2015-05-06 15:20
I will bring these at today's critique for further feedback. From that point, I will start designing.

In the meantime though, if you find photos of happy people, *pleease* share them :)

**Comment by secretrobotron** [comment] 2015-05-06 15:36
![img_20150506_112820376](https://cloud.githubusercontent.com/assets/403231/7496730/097f57d4-f3e4-11e4-879a-faf5f7bc5fdb.jpg)
![img_20150506_112916198](https://cloud.githubusercontent.com/assets/403231/7496732/0989dec0-f3e4-11e4-9b6e-8650692f16ba.jpg)
![img_20150506_112958788_hdr](https://cloud.githubusercontent.com/assets/403231/7496731/098963be-f3e4-11e4-82b8-923e9f5f5e5e.jpg)
![img_20150506_113024026](https://cloud.githubusercontent.com/assets/403231/7496733/098deab0-f3e4-11e4-94ed-9c2195d37b63.jpg)

**Comment by vazquez** [comment] 2015-05-07 21:28
### Design Update

@LauraReynal has fantastic photos so I decided to use them to make up this content. I separated the narrative geographically.

1. Kenya & Bangladesh
2. Rio De Janeiro
3. Elsewhere in the world

##### Map View 

![screenshot 2015-05-07 14 16 11](https://cloud.githubusercontent.com/assets/1119821/7526112/e3bba49a-f4c3-11e4-9dcd-c6effb1ee378.png)

##### Page View

![screenshot 2015-05-07 14 21 27](https://cloud.githubusercontent.com/assets/1119821/7526181/64917c02-f4c4-11e4-89ec-993cba6d4b7f.png)

---

Next, I'm going to make a cluster of photos in one of the corners of the map. I only have enough photos for one corner however.

![screenshot 2015-05-07 14 22 49](https://cloud.githubusercontent.com/assets/1119821/7526223/a511e67c-f4c4-11e4-8fa1-08f34f5e2d8a.png)

**Comment by xmatthewx** [comment] 2015-05-07 21:56
Great progress, great photos. Would love to see some clustered pages and avoid a cross †. The pages feel stiff with so much text. This is a good project to populate our gallery, but for the landing page and video, something more collaged will probably work better. Also -- the tool is good for tilting pictures and overlaying text, not very good for creating template-like pages. Have some fun with your layout.

**Comment by vazquez** [comment] 2015-05-07 22:02
Modified the structure to cluster more. I will wait for you to let me know if this is good to go before I begin modifying content as it very time consuming.

![screenshot 2015-05-07 15 01 24](https://cloud.githubusercontent.com/assets/1119821/7526811/1b49a690-f4ca-11e4-86b1-a2145a73b22b.png)

**Comment by cassiemc** [comment] 2015-05-07 22:04
Would think fewer pages to make sure the idea is really straightforward and conceptual. What is the minimum number of tiles to get the idea across? 

Also, as I mentioned yesterday, try to get this content to really emphasize the benefits of building something in this format / structure vs. in google docs, prezi, blog post, etc. It's still not clear to me how this concept is benefited by this structure. Maybe need to go back to the _______ in a ______ exercise.

**Comment by xmatthewx** [comment] 2015-05-08 13:29
One way to address @cassiemc's concern is to think about scale and cropping within each composition. A page with just a big smile. A page with 4 small photos collaged. A page with a huge word collage filling it (Clap along if you feel like happiness is the truth?). You could place the same picture 3 times transformed to different scales. Play around a bit before you methodically update the whole project. Make a page or two in picCollage to zero in on how it feels to make this on mobile.

**Comment by cassiemc** [comment] 2015-05-08 13:45
As a user, I'm not sure why I want to browse happy people though. What is this telling me? That happiness is universal around the world? Is there some kind of story connecting the people? what's the concept? I might just be grumpy :) but 'happy people' doesn't read to me as a concept. Maybe it is more "Happy expressions look the same on every continent" or "Happy people make a difference in the world" or "There's a lot to be happy about". Those are cheesy but you see where I'm going? A riff on the Happiness song would have been cool, and maybe there is even a more contemporary version of this that we could build on. Maybe you could work with Paul or Kevin to tweak the copy and pin this concept down, then you can work on simplifying.

**Comment by xmatthewx** [comment] 2015-05-08 14:22
The urgent task in this issue is to create content for the app landing page and video. If this project lives on in the app for remixing, that's a bonus, but that secondary goal should not slow us down. 

In these contexts, our audience will just see a fragment of this project zipping past. People don't need to understand the whole project. Their focus is on the platform and what it can do for them, not the project. 

The content should say to them: Webmaker is a place where you can meet cool people, capture the best moments of your life, and share all that with friends. Photos of smiling people are the quickest way to achieve that. 

I wholly agree that happiness and smiles are cheesy in writing (though Pharrell might disagree). On faces, they're nice.

**Comment by LauraReynal** [comment] 2015-05-08 14:57
What about the stories that users in Chicago designed on paper ? Would that be interesting to look at ?
the pro:
- they are real content ideas from teens 
- they are short and might be quick to design 
the cons 
- one is leveraging the non linear structure 
- 2 are not

**Comment by vazquez** [comment] 2015-05-19 19:42
##### Progress

- We reduced the scope of this project to only have a few pages
- We changes the aesthetic of the project to be more accurate to the things you can actually make with the app.
- We added rotations, wild colours for a more scrapbook feel.

Github is not processing images right now, so I'm posting a hard link to the screenshot of the project:
https://www.dropbox.com/s/it76zpc3wq5h58y/Screenshot%202015-05-19%2015.22.25.png?dl=0

**Comment by vazquez** [comment] 2015-05-19 19:43
![Uploading Screenshot 2015-05-19 15.22.25.png…]()

**Comment by thisandagain** [comment] 2015-05-20 23:46
Hey @vazquez looks like your most recent comp never came through. Now that adding new projects and the discovery API hookup has landed, do you want to take a crack at building this on-device?

**Comment by vazquez** [comment] 2015-05-25 16:34
@secretrobotron Here are the assets along with a map view for reference - https://dl.dropboxusercontent.com/u/43783651/Mozilla/Android/App%20Content.zip

Feel free to tweak it and make it robotronesque :rocket:

**Comment by secretrobotron** [comment] 2015-05-25 16:35
Yay :D. Thanks @vazquez.

**Comment by secretrobotron** [comment] 2015-05-25 17:32
Tried doing a bit of this just now. Need to hold off on creating this project until a couple of bugs are fixed (listed below).

**Comment by thisandagain** [comment] 2015-05-26 19:31
Great. Thanks @secretrobotron. Two of these have been flagged as critical and we are trying to resolve them now. #1999 is not a bug, and thus we'll need you to work within the constraints of the UI/UX. 
/cc @flukeout @xmatthewx

**Comment by secretrobotron** [comment] 2015-06-19 20:34
We have a few good examples to choose from now. :)

**Closed by secretrobotron** 2015-06-19 20:34 UTC
Labels: content, design
