### ISSUE TITLE
Borders - Fix the order of choices 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1892] opened 2015-05-18 14:58 UTC
Currently you choose the border width before the color. But choosing the color is choosing the border. 
We should inverse the 2 because it is counter logical.

**Comment by thisandagain** [comment] 2015-05-18 15:41
:+1: Agreed. Related to #1864

**Comment by LauraReynal** [comment] 2015-06-04 00:53
Came back as a problem during interviews yesterday @thisandagain

**Comment by LauraReynal** [comment] 2015-06-11 05:09
It does not seemed solved for me. It still feels counter logical.

**Comment by LauraReynal** [comment] 2015-06-11 05:12
Can you guys try ? 
Steps : 
- add image 
- try to change border 
=> 
you still have to 1 - scroll down - increase widht
2 - change color from preset color 
3 - go into tinker mode 

the logical way would be something like
- Add border 
- Changes the color 

It's not just me, it's also from all of the users, people miss the "increase width" and feel like there is a problem with our colors.

**Comment by k88hudson** [comment] 2015-06-11 14:30
@LauraReynal Hm, originally you asked to change the order from 1. width 2. colour to 1. colour 2. width (which was done), so I don't think the ordering here is the problem; it seems like the problem is that because both colour and border need to be changed from their defaults to be seen.

Should we maybe change the default border width to `1` or something?

What do you think @xmatthewx @vazquez

**Comment by xmatthewx** [comment] 2015-06-11 14:45
@k88hudson is correct. 

I propose: 
 - list color first, width second since color is more interesting and intuitive
 - but, when a color is picked, if width = 0, set width to 4px

Default borders are awesome on pics, but not great on transparent stickers.

**Comment by LauraReynal** [comment] 2015-06-11 14:46
Apologies for the confusion @k88hudson I think I got lost. :confused: 

The thing we can learn from this confusion is that users don't get it either way.

**Comment by vazquez** [comment] 2015-06-11 15:25
:bouquet: for everyone.

I agree with @xmatthewx's proposal.

**Comment by k88hudson** [comment] 2015-06-11 15:27
Note that if the default border is 0, and the default colour is transparent, it won't be seen

**Comment by k88hudson** [comment] 2015-06-11 15:28
@LauraReynal haha no apologies necessary ^_^ I was just trying to wrap my head around the problem :stuck_out_tongue_winking_eye:

**Comment by xmatthewx** [comment] 2015-06-11 15:36
If that's an easier way to get this done, then definitely yes, but I don't think that's preferred. 

It won't cover instances when someone reduces the border to zero and then changes the color. They might be more likely to understand the relationship at that point, but maybe not if they're just fiddling. We should keep the making experience as smooth as possible. Again, this is an ok corner to cut if necessary as we wrap up beta.

**Comment by k88hudson** [comment] 2015-06-11 15:37
Ah, good point :

**Comment by k88hudson** [comment] 2015-06-12 00:13
@LauraReynal ok, this has landed. Let me know if in Tomorrow's build this makes more sense

**Comment by k88hudson** [comment] 2015-06-12 21:05
@LauraReynal feel free to reopen if you still see issues

**Closed by k88hudson** 2015-06-12 21:05 UTC
Labels: feedback, in-review
