### ISSUE TITLE
Changing image does not work

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2119] opened 2015-06-09 05:18 UTC
Latest built : 
- new page
- adds image
- changes image 
- selects from the gallery 
nothing happens 
goes back to project page 
do it again 
nothing happens

**Comment by LauraReynal** [comment] 2015-06-09 05:19
Conditions : fully perfectly working wifi hotspot

**Comment by LauraReynal** [comment] 2015-06-09 05:20
cc / @thisandagain

**Comment by thisandagain** [comment] 2015-06-09 06:04
@k88hudson @Pomax Let's take look at this after stand-up

**Comment by LauraReynal** [comment] 2015-06-09 08:48
Here is a screen cast

https://docs.google.com/a/mozillafoundation.org/file/d/0B0X05aIHuAbeSXdHbkdjUGVpZFE/edit?usp=docslist_api

I hope it works I'm afk

**Comment by thisandagain** [comment] 2015-06-09 16:25
May be resolved in #2115

**Comment by k88hudson** [comment] 2015-06-09 19:05
@LauraReynal @thisandagain after landing #2115 this appears resolved. Can you confirm?

**Comment by secretrobotron** [comment] 2015-06-09 19:55
Just tried this on latest develop commit. Looks like a race condition.

**Comment by thisandagain** [comment] 2015-06-09 19:57
I can still produce the problem (albeit less frequently). Almost seems to be a regression to the problem that was plaguing us two weeks ago.

**Comment by k88hudson** [comment] 2015-06-09 20:01
What's happening is that when the editor activity is paused and resumed due to the camera, there is a race condition between data being reloaded from the API and receiving the `imageReady` call from Android.

**Comment by k88hudson** [comment] 2015-06-10 16:50
This should now be resolved

**Closed by k88hudson** 2015-06-10 16:50 UTC
Labels: bug, critical
