### ISSUE TITLE
When choosing a dark button background color, text switches to black

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-android#2278] opened 2015-06-18 10:45 UTC
In tinker mode, when choosing a button background color, the text starts our black on a light color background (which is good), then switches to white on medium brightness background (which is good) but if you make the color darker (heading towards black) the text switches back to black and becomes unreadable.

**Comment by xmatthewx** [comment] 2015-06-18 13:29
duplicate of #2240

**Closed by xmatthewx** 2015-06-18 13:29 UTC
Labels: bug
