### ISSUE TITLE
[MIGRATED] UI for Page Background Color

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1702] opened 2015-05-08 16:44 UTC
This [Page Background UX Diagram](https://dl.dropboxusercontent.com/u/109902/tiles/page-background.pdf) describes the UX for adding, manipulating and removing a page background image and color.

@xmatthewx Thoughts? Also, please assign to appropriate milestone if we've got it on the roadmap already.

**Comment by xmatthewx** [comment] 2015-05-08 17:56
Background color was included as a feature of Project/Page views, but was not listed as a specific feature on the roadmap. I will file it as Beta to make sure it gets done. 

Background photos will need to wait. We don't yet have any image support yet. We can post your UX to the backlog and label it for community contribution. 

![screenshot 2015-05-08 13 52 46](https://cloud.githubusercontent.com/assets/53411/7542290/8db76798-f589-11e4-9052-dbc3dc6abe41.png)

I think I like that you included an explicit confirm. I was concerned about blocking the tools. 
  
cc @vazquez

**Comment by vazquez** [comment] 2015-05-11 20:13
Is this a duplicate of #1541?

**Comment by flukeout** [comment] 2015-05-11 21:07
@vazquez Yeah - its, I'll unify them.

**Comment by flukeout** [comment] 2015-05-11 21:16
Moved to backlog as an enhancement since it deals with background images. We can revisit later.

**Comment by toolness** [comment] 2015-07-14 18:08
<a href="https://github.com/mozilla/webmaker-core/issues/63"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/63.
Please don't comment on it here.

**Closed by toolness** 2015-07-14 18:08 UTC
Labels: design, enhancement
