### ISSUE TITLE
Style regression: option buttons are no longer centered

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1884] opened 2015-05-15 23:51 UTC
![image](https://cloud.githubusercontent.com/assets/1455535/7663648/c45eabdc-fb3b-11e4-89ae-8f35ce4f0968.png)

**Comment by Pomax** [comment] 2015-05-16 00:11
duplicate of https://github.com/mozilla/webmaker-android/issues/1876

**Closed by Pomax** 2015-05-16 00:11 UTC
Labels: bug
