### ISSUE TITLE
Editing text in text editor moves entire app screen to the left

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1848] opened 2015-05-13 20:20 UTC
Whenever I click on the text to edit "Hello World", the whole screen moves over.

![screenshot 2015-05-13 16 18 25](https://cloud.githubusercontent.com/assets/403231/7620142/dedb56a6-f98b-11e4-83f3-e411f069f249.png)

**Comment by thisandagain** [comment] 2015-05-13 20:38
Duplicate of #1842

**Closed by thisandagain** 2015-05-13 20:38 UTC
Labels: bug
