### ISSUE TITLE
Fun glitch on Add Element view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1986] opened 2015-05-21 22:05 UTC
Steps to reproduce
* Tap Add Element
* Now, start tapping quickly anywhere else on the dark overlay
* You can get it to turn off and on indefinitely as long as you keep tapping!

cc @thisandagain

**Comment by thisandagain** [comment] 2015-05-21 22:24
Dupe of #1984

**Closed by thisandagain** 2015-05-21 22:24 UTC
Labels: bug, feedback

**Comment by flukeout** [comment] 2015-05-21 23:08
@thisandagain That's weird - I added this issue twice?! Damn
