### ISSUE TITLE
elements can show up in the wrong position on a page (offset/position bug?)

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1804] opened 2015-05-11 18:16 UTC
- open a project, tap on the premade page, tap edit button
- the elements look like they've been shifted up and left by half the page's height/width. 
- do not manipulate the elements
- go back to the projects view
- tap edit again
- the elements now look like they've been shifted right and down by half the page's height/width. 

Either the element offset, element position, or both, are wrong on first page view. This might be due to unknown page dimensions, or unknown element dimensions, or both, or something else entirely.

**Comment by xmatthewx** [comment] 2015-05-11 18:23
Probably related. Elements have wrong position in project view if they are not moved after they are added to default position in a page. 

 1. open a page and delete everything
 2. add any 2 elements. don't move them. 
 3. exit page. elements appear in top left of the page on map
 4. enter page
 5. move one of the elements
 6. exit page. moved element is positioned correctly. other element remains in top left

These elements appear to have no position, not an offset of half page height and width as I saw in an earlier bug.

**Comment by thisandagain** [comment] 2015-05-12 00:50
Duplicate of #1745

**Closed by thisandagain** 2015-05-12 00:50 UTC
Labels: bug, feedback
