### ISSUE TITLE
Sign Up - Duplicate username / email errors are quite bad

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2216] opened 2015-06-13 03:23 UTC
Users are presented with "Login database error" when attempting to create an account with either a username or email address collision.

![screenshot_2015-06-13-09-12-44](https://cloud.githubusercontent.com/assets/747641/8142816/b89160ae-1140-11e5-88ae-1c71cb0ad000.png)

/cc @LauraReynal

**Comment by k88hudson** [comment] 2015-06-13 05:26
This is a duplicate of https://github.com/mozilla/webmaker-android/issues/2110 (closing either is fine)

**Comment by cadecairos** [comment] 2015-06-16 21:12
mozilla/id.webmaker.org#321 only fixed this for login servers running SQLite, mozilla/id.webmaker.org#322 addresses the MariaDB/MySQL case

**Comment by cadecairos** [comment] 2015-06-17 14:35
Duplicate email/usernames now give meaningful feedback on prod/staging apps (although, it is in English only)

**Closed by cadecairos** 2015-06-17 14:35 UTC
Labels: bug, critical
