### ISSUE TITLE
page preview shows elements in the wrong place

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1808] opened 2015-05-11 18:34 UTC
- Go to an empty page in a project
- hit edit
- add a text element
- element shows as living in the middle of the page
- go back to project view
- element is shown in upper left corner.
- go back to page view
- element is in the same place as before
- drag element around and drop it in the center of the page
- go back to project view
- page preview now shows the correct positioning

**Comment by thisandagain** [comment] 2015-05-12 00:37
We have a bunch of issues describing this problem in different ways. Keeping this open for now as a unique STR.

**Comment by thisandagain** [comment] 2015-05-12 00:50
Duplicate of #1745

**Closed by thisandagain** 2015-05-12 00:50 UTC
Labels: bug, feedback
